### ISSUE TITLE
strsim or strsimpy or pystrsim?

### ISSUE THREAD

**Issue by fridde** [luozhouyang/python-string-similarity#11]
I am trying to work with your library (it looks promising and has great documentation), but get confused by the contradiction of strsimpy coexisting with strsim and pystrsim, having different version numbers but the same code and documentation.

Would you mind deleting some of these projects from PyPI or at least documenting the differences?

(Sorry for opening two separate issues, but I felt they addressed different problems)

**Comment by luozhouyang** [comment]
`strsim` is deprecated, use `strsimpy` instead. I have updated README to explain that.
