### ISSUE TITLE
Nondeclared dependency numpy

### ISSUE THREAD

**Issue by fridde** [luozhouyang/python-string-similarity#12]
When running ```strsimpy.levenshtein import Levenshtein``` I get the error ```ModuleNotFoundError: No module named 'numpy'``` which is correct as I haven't installed numpy on this machine.

I could write a pull request for your setup.py to state the dependencies, but maybe you are aware of more dependencies that should be declared?

(Sorry for opening two separate issues, but I felt they addressed different problems)

**Comment by luozhouyang** [comment]
Did you update to the latest version? The latest version does not require `numpy`.

```bash
conda activate python35

python35> pip install -U strsimpy
python35> python
Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 16:30:03)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from strsimpy.levenshtein import Levenshtein
>>>
>>> import strsimpy
>>> strsimpy.__version__
'0.1.3'
>>>
```
No exceptions occur.
