### ISSUE TITLE
speed of JaroWinkler

### ISSUE THREAD

**Issue by reza1615** [luozhouyang/python-string-similarity#22]
JaroWinkler is slower than jellyfish's implementation. Also, the results are different.
``` python
%%timeit
a = 'book egwrhgr rherh'
b = 'fvdaabavvvvvadvdvavavadfsfsdafvvav book teee'

import jellyfish
jellyfish.jaro_winkler(a,b) 
# 3.97 µs ± 169 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
# result > 0.35942760942760943

%%timeit
a = 'book egwrhgr rherh'
b = 'fvdaabavvvvvadvdvavavadfsfsdafvvav book teee'
from strsimpy.jaro_winkler import JaroWinkler
jarowinkler = JaroWinkler()
jarowinkler.distance(a,b)
# 69.8 µs ± 706 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
# result > 0.6405723905723906
```

**Comment by luozhouyang** [comment]
I am not sure why the results are different, but `strsimpy` gets the same results with [java-string-similarity/JaroWinklerTest.java](https://github.com/tdebatty/java-string-similarity/blob/master/src/test/java/info/debatty/java/stringsimilarity/JaroWinklerTest.java):
```bash
>>> jarowinkler.similarity('My string', 'My tsring')
0.9740740740740741
>>> jarowinkler.similarity('My string', 'My ntrisg')
0.8962962962962963
```

`jellyfish` has both Python and C implementation of `JaroWinkler`. Which implementation did you use for comparision?

**Comment by reza1615** [comment]
I used python implementation

**Comment by luozhouyang** [comment]
I know why the two results are different. `jellyfish.jaro_winkler(a, b)` calculate the similarity between `a` and `b`, but `jarowinkler.distance(a,b)` calculate the distance between `a` and `b`. If you use `jarowinkler.similarity(a,b)`, you can get the same result.

**Comment by luozhouyang** [comment]
`jellyfish` use the C implementation of `JaroWinkler` as default. Here is the code in [hellyfish/\_\_init\_\_.py](https://github.com/jamesturk/jellyfish/blob/master/jellyfish/__init__.py)

```python
import warnings

try:
    from .cjellyfish import *  # noqa

    library = "C"
except ImportError:
    from ._jellyfish import *  # noqa

    library = "Python"

```
