### ISSUE TITLE
Convert distance to probability

### ISSUE THREAD

**Issue by jtlz2** [luozhouyang/python-string-similarity#6]
This is a broader question - but do you have any insight on how to convert e.g. Levenshtein distance to probability? I want to combine the edit distance with prior information on the background population - and it's not clear to me how to combine the two metrics. Thanks!

**Comment by sangmoon** [comment]
Hi I am a github traveler, and saw your question by chance. I become curious too and look up SO.

https://stackoverflow.com/questions/955110/similarity-string-comparison-in-java/16018452#16018452

It says there can be several ways to change edit distance to probability, it's a common way(used in many library) to  to measure how much (in %) you'd have to change the longer string to turn it into the shorter.

I hope this help you!

**Comment by luozhouyang** [comment]
Thanks @sangmoon.
@jtlz2 you can have a try.
