### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by dur41d** [luozhouyang/python-string-similarity#7]
I installed via pip and I'm getting ModuleNotFoundError: No module named 'similarity'. Here is my code below. I got this error on 2 machines. I'm using python 3.7.3 64-bit and python 3.5 32-bit. 

```
from similarity.levenshtein import Levenshtein

levenshtein = Levenshtein()
print(levenshtein.distance('My string', 'My $string'))
print(levenshtein.distance('My string', 'My $string'))
print(levenshtein.distance('My string', 'My $string'))

```

**Comment by dur41d** [comment]
The wierd thing is that when I execute the code in python console line by line it works! I wonder what's going on?

**Comment by luozhouyang** [comment]
hi @dur41d , I am not sure what caused the problem, but I rename the package to **strsimpy** today, for avoid misunderstanding. You can upgrade to the latest version (of **strsimpy**) and try again.
